# Generated by Django 5.0b1 on 2023-10-29 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="model_amount_name",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="model_description_name",
                    ),
                ),
                (
                    "debtor",
                    models.CharField(
                        choices=[("P1", "Person 1"), ("P2", "Person 2")],
                        max_length=2,
                        verbose_name="model_debtor_name",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="model_created_at_name"
                    ),
                ),
            ],
            options={
                "verbose_name": "model_debt_name",
            },
        ),
    ]
