# Generated by Django 5.0b1 on 2023-11-04 14:45

import django.core.validators
from django.db import migrations

import iou.models


class Migration(migrations.Migration):
    dependencies = [
        ("iou", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debt",
            name="amount",
            field=iou.models.PositiveDecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="model_amount_name",
            ),
        ),
    ]
