# Generated by Django 6.0.4 on 2026-04-18 20:29
# https://docs.djangoproject.com/en/dev/howto/writing-migrations/#migrations-that-add-unique-fields
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iou", "0003_user"),
    ]

    def gen_uuid(apps, schema_editor):
        User = apps.get_model("iou", "User")
        for row in User.objects.all():
            row.uuid = uuid.uuid4()
            row.save(update_fields=["uuid"])

    operations = [
        # Add the uuid field as nullable.
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(editable=False, null=True),
        ),
        # Populate the uuid field.
        migrations.RunPython(
            gen_uuid,
            reverse_code=migrations.RunPython.noop,
        ),
        # Apply stricter constraints to the uuid field.
        migrations.AlterField(
            model_name="User",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
