# Generated by Django 6.0.4 on 2026-05-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passkeys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="last_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
