name: Code check
on:
  pull_request:
  push:
      branches:
        - main
jobs:
  Check:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install -r requirements/dev.txt --upgrade pip && \
          sudo apt update && sudo apt install -y gettext
      - name: Create fake .env file
        run: cat .env.template|sed -e 's/DEBUG=false/DEBUG=true/' > .env
      - name: Prepare database
        run: |
          python manage.py migrate
      - name: Prepare resources
        run: |
          django-admin compilemessages && \
          python manage.py collectstatic --clear --no-input
      - name: Run codecheck
        run: bash scripts/codecheck.sh
      - name: Run tests
        run: bash -x scripts/run_tests.sh
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'reports/junit.xml'
      - name: Archive reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: reports
